### ISSUE TITLE
Multi armature link animation path error

### ISSUE THREAD

**Issue by NovaVoidHowl** [NovaVoidHowl/CVRFury#10]
When there are two or more armature links per DSU then the paths end up stacking in the created animation clips.
eg 

```yaml
 - curve:
      serializedVersion: 2
      m_Curve:
      - serializedVersion: 3
        time: 0
        value: {x: 0, y: 0, z: 0}
        inSlope: {x: 0, y: 0, z: 0}
        outSlope: {x: 0, y: 0, z: 0}
        tangentMode: 0
        weightedMode: 0
        inWeight: {x: 0, y: 0.33333334, z: 0.33333334}
        outWeight: {x: 0, y: 0.33333334, z: 0.33333334}
      m_PreInfinity: 2
      m_PostInfinity: 2
      m_RotationOrder: 4
    path: skeleton/hips/spine/chest/shoulder_l/upperarm_l/forearm_l/hand_l/CVRF_Addon_0/[CVRF_D0]_Clock/hips/CVRF_Addon_0/[CVRF_D0]_Hip/HipRotation/HeadClone/Monitors/Keyboard
 ```
